apiVersion: v2
name: hauler-helm
version: 2.0.8
appVersion: 1.2.5

type: application
description: Hauler Helm Chart - Airgap Swiss Army Knife
icon: https://raw.githubusercontent.com/hauler-dev/hauler/main/static/rgs-hauler-logo-icon.svg

home: https://github.com/hauler-dev
sources:
  - https://github.com/hauler-dev/hauler
  - https://github.com/hauler-dev/hauler-helm

maintainers:
  - name: Rancher Government
    email: hauler@ranchergovernment.com
    url: https://ranchergovernment.com

annotations:
  classification: UNCLASSIFIED
